---
title: "FA21_Search_Jan2020_JR"
author: "Office of Marketing and Brand Management"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library(dplyr)
library(salesforcer)
library(knitr)
library(RForcecom)
```


```{r cars}
username <- "christine.iyer@maine.edu"
password <- "1Edithandoliver"
securityToken <- "iFhpXgaXnuP3L5PQr69Zw2yOy"
instanceURL <- "https://login.salesforce.com/"
apiVersion <- "44.0"

#auth <- sf_auth(username = username, password = password, security_token = securityToken,
  #login_url = getOption("https://login.salesforce.com/"))



session <- sf_auth(username, password, securityToken, instanceURL, apiVersion)
```

```{r}
#sf_auth()
```

```{r}

username <- "christine.iyer@maine.edu"
password <- "1EdithandoliveriFhpXgaXnuP3L5PQr69Zw2yOy"
#securityToken <- ""
instanceURL <- "https://na24.salesforce.com/"
apiVersion <- "44.0"





session <- rforcecom.login(username, password, instanceURL,apiVersion  ) 
```


```{r use this}
my_soql <- sprintf("SELECT Id,
                           CreatedDate,
                           Email, 
                           FirstName, 
                           LastName,
                           TargetX_SRMb__Status__c, TargetX_SRMb__Student_Type__c,
                           TargetX_SRMb__Anticipated_Start_Term__c,
                           TargetX_SRMb__Anticipated_Start_Term_Year__c, 
                           App_Application_Date__c,  
                           TargetX_SRMb__Gender__c,  
                           TargetX_SRMb__Last_Data_Input_Source__c,                                                                Initial_Source_Date__c, 
                           Initial_Referral_Source__c, 
                           Recruiting_Category__c,
                           Ref__c, 
                           Primary_State_Code__c
                           
                    FROM Contact 
                    WHERE DAY_ONLY(CreatedDate) > 2020-02-25 
                    AND DAY_ONLY(CreatedDate) < 2020-03-13 
                    AND TargetX_SRMb__Status__c != 'Lead' 
                    AND (Lead_Segment_College_Board__c != ' ' 
                    OR 	Lead_Segment_NRCCUA__c  != ' ') 
                    AND TargetX_SRMb__Anticipated_Start_Year__c = 2021")

queried_records <- sf_query(my_soql)
```
 



**January 2020**

```{r}

# This is not going to work because Recruiting category is no longer a reliable field. A new ifelse clause needs to be written to determine the initial source 
LeadsUploaded <- read.csv("C:/Users/christine.iyer/Box/Search/FY20_Search/FY20_Combined_Search_Feb_March/FY20_Feb_Search_Upload_DeDuped.csv", header = T, stringsAsFactors = F)

unique(LeadsUploaded$Recruiting.Category)

LeadsUploaded <- LeadsUploaded 
#%>% filter(Anticipated.Start.Year != 2020)

# LeadsUploaded %>% group_by(Email, Lead.Segment.College.Board, Lead.Segment.NRCCUA) %>% summarise(n = n()) %>% filter(n>1)

trythis <- merge(LeadsUploaded, queried_records, by = "Email" )
trythis <- trythis %>% mutate(DateCollected = Sys.Date())

#trythis
# Don't forget to change the date!


#write.csv(trythis,"C:/Users/christine.iyer/Box/Search/FY20_Search/FY20_Combined_Search_Feb_March/Junior_Conversions/Conversions_4-06-20_DeDuped", row.names = F)

# trythis %>% 
#   #filter(Student.Stage == "Lead") %>% 
#   mutate(Name = paste0(Last.Name, ", ", First.Name)) %>% 
#   group_by(Student.Stage,TargetX_SRMb__Status__c,  Email, Created.Date, Ref__c, Recruiting_Category__c,Recruiting.Category, Lead.Segment.College.Board, Lead.Segment.NRCCUA) %>% summarise(n = n())

```


```{r}
trythis1 <- trythis %>% group_by(Primary_State_Code__c) %>% summarise(Inqs = n())
```


```{r}
# kable(trythis1 %>% mutate(Recruiting.Category_Geo = ifelse(Primary_State_Code__c == "ME", "In_State", "Out-Of-State")) %>% group_by(Recruiting.Category_Geo) %>% summarise(Inqs = sum(Inqs)))

```

```{r}
LeadsUploaded <- LeadsUploaded %>%  mutate(
  Vendor = ifelse(grepl('^N', Recruiting.Category), 'NRCCUA', 'College Board'),
   Class = ifelse(grepl('J', Recruiting.Category), 'Junior', 
                  ifelse(grepl('SR', Recruiting.Category),'Senior', "Sophomore")),
    Geo = ifelse(grepl('O', Recruiting.Category), 'Out-of-State', 'In-State'))
Leads <- LeadsUploaded %>% group_by(Vendor,Class ,Geo) %>% summarise(Leads = n())
```

```{r}
Inquiries <- LeadsUploaded %>% filter(Student.Stage != "Lead")

```



```{r}
unique(Inquiries$App.Application.Status)
ConfirmedWords <- c("Confirmed", "Withdrawn (After Confirmed)")
AdmittedWords <- c("Withdrawn (After Admitted)", "Admitted (Not Confirmed)" )

Inquiries <- Inquiries %>% 
mutate(ApplicationStatus =
  ifelse(App.Application.Status %in% AdmittedWords, "Admitted",
         ifelse(App.Application.Status %in% ConfirmedWords, "Confirmed",
                ifelse(App.Application.Status == "Enrolled", "Enrolled",
                       ifelse(App.Application.Status == "", "Inquiry", "Applied")))))


#trythis
# Don't forget to change the date!

# write.csv(Inquiries,"C:/Users/christine.iyer/Box/Search/FY20_Search/Search_Oct_2017/Conversions_October2017_4-6-20.csv", row.names = F)

```

### Conversion Summary as of `r Sys.Date()`

```{r}

Inquiries1 <- Inquiries %>% group_by(Vendor,Class,Geo, Student.Stage, ApplicationStatus) %>% summarise(Inquiries = n())
# Final number inquiries
Inquiries2 <- Inquiries1 %>% group_by(Vendor, Class, Geo) %>% summarise(Inquiries = sum(Inquiries))

```

```{r}
Applicants <- Inquiries1 %>% 
  filter(ApplicationStatus!= "Inquiry") %>% 
  group_by(Vendor, Class,Geo,  ApplicationStatus) %>% 
  summarise(Apps = sum(Inquiries)) 
#Final number Applicants

Applicants1 <- Applicants %>% 
  group_by(Vendor,  Class,Geo) %>% 
  summarise(Applicants = sum(Apps))
# Applicants1[8,1] <- "NRCCUA"
# Applicants1[8,2] <- "Senior"
# Applicants1[8,3] <- "Out-of_State"
# Applicants1[8,4] <- 0

```



```{r}

Admits <- Applicants %>% 
  filter(ApplicationStatus != "Applied") %>% 
  group_by(Vendor, Class, Geo, ApplicationStatus) %>% 
  summarise(Admits = sum(Apps))

#FOr number of Admits

Admits1 <- Admits %>% 
  group_by(Vendor,  Geo) %>% 
  summarise(Admits = sum(Admits))

# Admits1[8,1] <- "NRCCUA"
# Admits1[8,2] <- "Senior"
# Admits1[8,3] <- "Out-of_State"
# Admits1[8,4] <- 0

```


```{r }

Confirms <- Admits %>% 
  filter(ApplicationStatus != "Admitted") %>% 
  group_by(Vendor, Class, Geo, ApplicationStatus) %>% 
  summarise(Confirms = sum(Admits))

#FOr number of Admits

Confirms1 <- Confirms %>% 
  group_by(Vendor,Class, Geo) %>% 
  summarise(Confirms = sum(Confirms))
# Confirms1[8,1] <- "NRCCUA"
# Confirms1[8,2] <- "Senior"
# Confirms1[8,3] <- "Out-of_State"
# Confirms1[8,4] <- 0

```

```{r}
#FOr number of Enrolls

Enrolls <- Confirms %>% 
  filter(ApplicationStatus == "Enrolled") %>% 
  group_by(Vendor, Class, Geo) %>% 
  summarise(Enrolls = sum(Confirms))

# Enrolls[8,1] <- "NRCCUA"
# Enrolls[8,2] <- "Senior"
# Enrolls[8,3] <- "Out-of_State"
# Enrolls[8,4] <- 0

```

__Inquiries__

```{r}
kable(left_join(Inquiries2, Leads) %>% select(Vendor, Class, Geo, Leads, Inquiries))
```
```{r}
#Filling in blanks because there are only
```


```{r eval=FALSE, include=FALSE}


Funnel <- cbind.data.frame(Leads, Inquiries2
                           , Applicants1, Admits1, Confirms1, Enrolls
                           )
```




```{r eval=FALSE, include=FALSE}

Funnel <- Funnel[, c(1:3, 6,9, 12, 15, 18)]
```






```{r eval=FALSE, include=FALSE}

nwew <- Funnel %>% 
  mutate(Inquiry_Yield = 
          paste0(round(Inquiries/Leads * 100,2), "%"),
         App_Yield = 
          paste0(round(Applicants/Leads * 100,2), "%"), 
         Leads = prettyNum(Leads, big.mark = ",")) %>% 
  select(Vendor,  Geo, Leads, Inquiries, Applicants, Admits, Confirms, Enrolls, Inquiry_Yield, App_Yield)


        
```





```{r eval=FALSE, include=FALSE}
##**In-State Senior**

kable(nwew %>% filter(Geo == "In-State")%>% 
        select(Vendor:App_Yield)) 
```



```{r eval=FALSE, include=FALSE}
#**Out-of-State Senior **
kable(nwew %>% filter(Geo == "Out-of-State")%>% 
        select(Vendor:App_Yield)) 
```

